services:
  middleware-internal:
    image: ${DOCKERHUB_NS:-tv30}/tv30-gateway-validation-middleware-internal:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: middleware-internal
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - KRAKEND_CONFIG=/etc/krakend/krakend.json
    volumes:
      - ../krakenD_internal/krakend.json:/etc/krakend/krakend.json:ro
    restart: unless-stopped
    networks:
      - ginga_net

networks:
  ginga_net:
    name: ginga_net
    driver: bridge
