version: '3.8'

services:
  krakend-external:
    image: ${DOCKERHUB_NS:-tv30}/tv30-gatewayhttps:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ../dockerfiles/gatewayhttps.Dockerfile
    container_name: krakend-external
    ports:
      - "44643:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ginga_net

networks:
  ginga_net:
    name: ginga_net
    driver: bridge
