version: '3.8'

services:
  krakend-external:
    image: devopsfaith/krakend:2.7
    container_name: krakend-external
    ports:
      - "44643:8080"
    volumes:
      - ./${KRAKEND_EXT_CFG:-krakend.json}:/etc/krakend/krakend.json
      - ./plugins:/etc/krakend/plugins
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ginga_net

networks:
  ginga_net:
    name: ginga_net
    driver: bridge
