services:
  validation-middleware:
    image: ${DOCKERHUB_NS:-tv30}/tv30-validation-middleware:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validation-middleware
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-0123456789}
      - JWT_ISSUER=${JWT_ISSUER:-GenericIssuer}
      - PORT=3000
      - KRAKEND_CONFIG=/etc/krakend/krakend.json
    volumes:
      - ../krakenD_external/krakend.json:/etc/krakend/krakend.json:ro
    restart: unless-stopped
    networks:
      - ginga_net

networks:
  ginga_net:
    name: ginga_net
    driver: bridge
