services:
  krakend-internal:
    image: ${DOCKERHUB_NS:-tv30}/tv30-gatewayhttp:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ../dockerfiles/gatewayhttp.Dockerfile
    container_name: krakend-internal
    ports:
      - "44642:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ginga_net

networks:
  ginga_net:
    name: ginga_net
    driver: bridge
